package ec.edu.ups.PachoRobertoCajeroJEE.Soap;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-02-05T12:53:16.762-05:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://services.PachoRobertoSriJEE.ups.edu.ec/", name = "ClienteServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface ClienteServiceSOAP {

    @WebMethod
    @RequestWrapper(localName = "saludar", targetNamespace = "http://services.PachoRobertoSriJEE.ups.edu.ec/", className = "ec.edu.ups.PachoRobertoCajeroJEE.Soap.Saludar")
    @ResponseWrapper(localName = "saludarResponse", targetNamespace = "http://services.PachoRobertoSriJEE.ups.edu.ec/", className = "ec.edu.ups.PachoRobertoCajeroJEE.Soap.SaludarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String saludar();
}
