
package ec.edu.ups.PachoRobertoCajeroJEE.Soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2021-02-05T12:53:16.681-05:00
 * Generated source version: 2.7.9
 * 
 */
public final class ClienteServiceSOAP_ClienteServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.PachoRobertoSriJEE.ups.edu.ec/", "ClienteServiceSOAPService");

    private ClienteServiceSOAP_ClienteServiceSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClienteServiceSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ClienteServiceSOAPService ss = new ClienteServiceSOAPService(wsdlURL, SERVICE_NAME);
        ClienteServiceSOAP port = ss.getClienteServiceSOAPPort();  
        
        {
        System.out.println("Invoking saludar...");
        java.lang.String _saludar__return = port.saludar();
        System.out.println("saludar.result=" + _saludar__return);


        }

        System.exit(0);
    }

}
